version: "3.4"

networks:
  webpage_for_rpi-dev:
    driver: bridge

services:
  webpage_for_rpi:
    image: webpage_for_rpi:latest
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres; port=5432; database=WEBPAGE_FOR_RPI; username=postgres; password=postgres"
    networks:
      - webpage_for_rpi-dev
        
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "WEBPAGE_FOR_RPI"
    networks:
      - webpage_for_rpi-dev
volumes:
  db_volume: