version: '3'
services:
  webpage_for_rpi:
    build: .
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=WEBPAGE_FOR_RPI
      - POSTHRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data:
